# Default configuration for the ReasoningBank library

# Memory backend settings
memory:
  # The type of memory backend to use. Options: "chroma", "json"
  backend: "chroma"

  # Settings for the ChromaDB backend
  chroma:
    collection_name: "reasoning_bank"

  # Settings for the JSON backend
  json:
    filepath: "memory.json"

# Embedding model settings
embedding_model:
  # The embedding model to use. Options: "gemini-embedding-001", "sentence-transformers"
  model_name: "embeddinggemma:300m"
  
  # The name of the sentence-transformer model to use, if model_name is "sentence-transformers"
  st_model_name: "all-MiniLM-L6-v2"

# LLM settings
llm:
  # The LLM provider to use. Options: "ollama", "langchain.llms.Fake"
  provider: "ollama"

  # The model to use, if the provider is "ollama"
  model: "gemma3:270m"
